Feature/rest
MaksLaptsev/springBootHW pull request #1
Opened 2023-12-01 17:55 UTC by MaksLaptsev

Task complited

2023-12-23 15:42 UTC, Akizmostr requested changes

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/controller/ChannelController.java
> +    public ResponseEntity<ChannelResponseFull> update(@RequestParam @NotNull Long channelId,
channelId лучше в PathVariable

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/controller/ChannelController.java
> +    public ResponseEntity<ChannelResponseFull> save(@RequestParam @NotNull Long authorId,
authorId в принципе можно и в дто всунуть

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/service/impl/UserServiceImpl.java
> +                .orElseThrow(()-> new PersonNotFoundException("Person with id: %s not found".formatted(id)));
Для чего тут saveAndFlush?
Это тот же save, только в конце еще происходит flush всего persistence контекста. Здесь это тебе явно не нужно и ухудшает производительность. Этот метод не стоит использовать, кроме случаев, когда ты вручную управляешь flush mode в своем контексте или еще по каким-то причинам ты точно уверен в своих намерениях)
Просто дергай save и будет тебе счастье.

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/service/impl/UserServiceImpl.java
> +                .map(u-> userMapper.fromRequest(user,id))
На будущее: в mapstruct есть возможность обновлять существующие объекты - аннотация MappingTarget

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/service/impl/UserServiceImpl.java
> +    }
Самому писать конструктор не нужно: в ломбоке есть аннотация @RequiredArgsConstructor

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/mapper/ChannelListMapper.java
> +    List<ChannelResponseOnlyNames> toResponseOnlyNames(List<Channel> channels);
Выносить их в отдельный маппер не обязательно было. Эти маппинги можно писать параллельно со всеми остальными

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/mapper/ChannelMapper.java
> +    public abstract Channel updateFromRequest(ChannelRequest request, Channel channel);
все строчки слиплись

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/service/impl/FileService.java
> +}
Неиспользуемый метод

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/controller/UserController.java
> +    }
ResponseEntity возвращать, в принципе, необязательно. Любой успешный запрос автоматически имеет статус 200, а если нужен другой статус - есть аннотация ResponseStatus - ее можно вешать как в обычных контроллерах, так и в ControllerAdvice

2023-12-23 15:42 UTC, Akizmostr commented on src/main/java/ru/clevertec/springboothw/repository/ChannelRepository.java
> +    List<Channel> findAllByNameContainingIgnoreCaseAndLanguageContainingIgnoreCaseAndAndCategoryContainingIgnoreCase(String name, String language, String category, Pageable pageable);
Могу как альтернативу предложить использовать Specification в связке с criteria api. Такой подход более универсальный и дает больше возможностей для настройки.

2024-01-17 06:44 UTC, closed without merging

2024-01-17 06:44 UTC, MaksLaptsev commented
close